/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.6.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as listMessages from "../listMessages";
import type * as listResponses from "../listResponses";
import type * as sendMessage from "../sendMessage";
import type * as sendResponse from "../sendResponse";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  listMessages: typeof listMessages;
  listResponses: typeof listResponses;
  sendMessage: typeof sendMessage;
  sendResponse: typeof sendResponse;
}>;
